### ISSUE TITLE
Closes, even with notification "hack" as described in app

### ISSUE THREAD

**Issue by paradox460** [MohammadAdib/Roundr#2]
I set my phone to hide notifications from RoundR, but leave it enabled, and the app keeps dying.

Phone: Verizon Galaxy Nexus running Cyanogenmod nightly and Franko Kernel

**Comment by MohammadAdib** [comment]
My friend has a Galaxy Nexus with CM10.1 and Franco.Kernel yet he doesn't experience this issue with the notification hidden.

**Comment by paradox460** [comment]
Since I reported the issue, it hasn't appeared again. Feel free to close, I
guess I was just being a hypochondriac.

**Comment by HyenaSpace** [comment]
I've been running into this recently ever since the update to allow hiding the notification with root options. App just silently dies somewhere in the background,and I never saw it do this using the 4.2 Notification toggle in app info.
Using CM10.1.2 on a Nexus 4. Short of log catting everything, is there an easy way to provide log info about it? It seems to die at random.

**Comment by f1vefour** [comment]
It is dying from an OOM situation, the only sure way to stop this is 
install the Xposed framework beta and the App Settings module. In the App 
Settings module there is an option to make any app Resident.

**Comment by HyenaSpace** [comment]
I know that it's dying in an OOM issue, but isn't that exactly what the foreground service is supposed to prevent? I had zero issues with hiding the service by toggling off show notifications, but the new root method doesn't actually seem to be keeping the foreground service from being killed.

If the new "improved" method of hiding it requires root, but it still dies even with root being used to hide it, then something somewhere seems to be not working properly...

My understanding was that the root method hides the notification but keeps the app alive via the now hidden foreground service which keeps Android from killing it when OOM.

**Comment by f1vefour** [comment]
Like I said, there is no other way I know of other than using Xposed.

Root or not. I use AIDE all the time and tried everything to prevent it 
from dying including moving it to /system/app but in the end Xposed is what 
allowed me to accomplish this.
