### ISSUE TITLE
New Notification layout doesn't match normal notification layouts

### ISSUE THREAD

**Issue by burntcookie90** [MohammadAdib/Roundr#3]
As seen here: https://www.dropbox.com/s/hkrrb4rvpqskqfv/2013-04-18%2010.58.08.png

wouldn't a simple icon like http://i.imgur.com/lP1ArJr.png be enough?

**Comment by MohammadAdib** [comment]
I like it my way

**Comment by MohammadAdib** [comment]
You can fork roundr and just remove the setContent in notification.

**Comment by burntcookie90** [comment]
Fair enough, thanks for the great application!
